title = Industrial Survival
author = Raphael Steffes
description = A realistic industrial survival game focused on automation, exploration, resources and complex production chains.
min_minetest_version = 5.16
textdomain = game_description
