name = st_terrain
description = Realistischer Weltgenerator für das STI-Game. Geologisch korrekte Gesteinsschichtung und Erzverteilung basierend auf sti_core.
depends = sti_core
optional_depends = default
